/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

import Data.Szerzodes;
import Data.Ugyfel;
import Hibernate.NewHibernateUtil;
import Logic.ANet;
import Logic.ASzerzodes;
import Logic.ATelefon;
import Logic.ATv;
import Logic.AUgyfel;
import Logic.Egyenleg;
import Logic.Kedvezmeny;
import java.util.ArrayList;
import static java.util.Collections.list;
import java.util.List;
import java.util.Vector;

import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import org.hibernate.HibernateException;
import org.hibernate.Query;
import org.hibernate.Session;

/**
 *
 * @author Imre
 */
public class SzolgFelvetel extends javax.swing.JFrame {

    private static String nevKeres = "from Ugyfel u where nev like '%";
    private static String folyoKeres = "from Ugyfel u where folyosz like '%";

    private void exeNevKeres() {

        executeHQLQuery(nevKeres + tfNev.getText() + "%'");
    }

    private void exeOsztalyKeres() {

        executeHQLQuery(folyoKeres + tfFolyo.getText() + "%'");

    }

    /**
     * Creates new form SzolgFelvetel
     */
    public SzolgFelvetel() {

        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        szolgList = new javax.swing.JList<>();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        tfNev = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        tfFolyo = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        jButton4 = new javax.swing.JButton();
        tfuzi = new javax.swing.JTextField();
        tfValasztott = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        btSelect = new javax.swing.JButton();
        szolgValaszt = new javax.swing.JButton();
        jScrollPane5 = new javax.swing.JScrollPane();
        csomagok = new javax.swing.JTable();
        jLabel7 = new javax.swing.JLabel();
        tfvalasztottCsomag = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        tfValasztottSzerzodes = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableSzerzodes = new javax.swing.JTable();
        SzerzSzelekt = new javax.swing.JButton();
        kiSzerSzam = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 255));

        szolgList.setModel(new javax.swing.AbstractListModel<String>() {
            String[] strings = { "TV", "Telefon", "Internet" };
            public int getSize() { return strings.length; }
            public String getElementAt(int i) { return strings[i]; }
        });
        szolgList.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        szolgList.setToolTipText("");
        jScrollPane1.setViewportView(szolgList);

        jLabel1.setText("A felvenni/törölni kívánt Szolgáltatás");

        jLabel2.setText("Csomagok");

        jButton1.setText("Felvesz");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Mégse");

        jLabel3.setText("Név");

        jLabel4.setText("Folyószámla");

        jLabel5.setText("Szerződés");

        jButton3.setText("Keres");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Folyószámla", "Név", "Cím"
            }
        ));
        jScrollPane4.setViewportView(table);

        jButton4.setText("Lemond");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel6.setText("A választott folyószámla");

        btSelect.setText("Select");
        btSelect.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btSelectActionPerformed(evt);
            }
        });

        szolgValaszt.setText("Választ");
        szolgValaszt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                szolgValasztActionPerformed(evt);
            }
        });

        csomagok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null},
                {null, null, null},
                {null, null, null},
                {null, null, null}
            },
            new String [] {
                "Azonosító", "Csomagnév", "Havi díj"
            }
        ));
        jScrollPane5.setViewportView(csomagok);

        jLabel7.setText("A választott csomag azonosítója:");

        jLabel8.setText("A kezelni kívánt  kiválasztott szerződés száma: (ha uresen hagyod = új szerződés lesz!)");

        tableSzerzodes.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Szerződésszám", "TV csomag", "Telefon csomag", "Internet", "Fix Ip"
            }
        ));
        jScrollPane2.setViewportView(tableSzerzodes);

        SzerzSzelekt.setText("Select");
        SzerzSzelekt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SzerzSzelektActionPerformed(evt);
            }
        });

        kiSzerSzam.setText("0");

        jLabel9.setText("Kiválasztott szerződés száma: ");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(56, 56, 56)
                                .addComponent(jLabel5))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(20, 20, 20)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel8)
                                        .addGap(29, 29, 29)
                                        .addComponent(tfValasztottSzerzodes, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(43, 43, 43)
                                        .addComponent(SzerzSzelekt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel6)
                                        .addGap(38, 38, 38)
                                        .addComponent(tfValasztott, javax.swing.GroupLayout.PREFERRED_SIZE, 63, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(30, 30, 30)
                                        .addComponent(btSelect))
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addGap(24, 24, 24)
                                        .addComponent(kiSzerSzam, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 58, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(35, 35, 35)
                                        .addComponent(szolgValaszt)))))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(125, 125, 125)
                                .addComponent(jLabel2))
                            .addGroup(layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 423, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(310, 310, 310)
                        .addComponent(jButton3)))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jButton2)
                .addGap(33, 33, 33))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(32, 32, 32)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel4)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(tfFolyo, javax.swing.GroupLayout.DEFAULT_SIZE, 166, Short.MAX_VALUE)
                            .addComponent(tfNev)))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(tfuzi, javax.swing.GroupLayout.PREFERRED_SIZE, 622, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 911, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(249, 249, 249)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(321, 321, 321)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabel7)
                                .addGap(34, 34, 34)
                                .addComponent(tfvalasztottCsomag, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(93, 93, 93)
                                .addComponent(jButton1)))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(52, 52, 52)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfNev, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addGap(3, 3, 3)
                .addComponent(jButton3)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFolyo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4))
                .addGap(34, 34, 34)
                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(tfuzi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(tfValasztott, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btSelect))
                .addGap(46, 46, 46)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(tfValasztottSzerzodes, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(SzerzSzelekt))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 0, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel9)
                            .addComponent(kiSzerSzam, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(250, 250, 250))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jScrollPane5, javax.swing.GroupLayout.PREFERRED_SIZE, 106, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(34, 34, 34))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(54, 62, Short.MAX_VALUE)
                                .addComponent(jLabel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(47, 47, 47)
                                        .addComponent(szolgValaszt))
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(33, 33, 33)
                                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(50, 50, 50)))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel7)
                            .addComponent(tfvalasztottCsomag, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1))
                        .addGap(41, 41, 41)
                        .addComponent(jButton4)
                        .addGap(59, 59, 59)))
                .addComponent(jButton2)
                .addGap(20, 20, 20))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed

        boolean f = true;
        int folyo = -1;
        try {
            folyo = Integer.parseInt(tfFolyo.getText());
            f = true;

        } catch (Exception e) {
            f = false;
        }

        if (!tfNev.getText().isEmpty()) {

            exeNevKeres();

        } else if (f && !tfFolyo.getText().isEmpty()) {

            exeOsztalyKeres();

        } else {
            JOptionPane.showMessageDialog(rootPane, "Nem adtál meg semmit vagy a Folyószámlához nem SZÁMot adtál meg! Javítsd!");
        }        // TODO add your handling code here:
    }//GEN-LAST:event_jButton3ActionPerformed

    private void btSelectActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btSelectActionPerformed

        Vector<String> fejlec = new Vector<>();
        fejlec.add("Szerződés szám");
        fejlec.add("Tv csomag");
        fejlec.add("Telefon csomag");
        fejlec.add("Internet csomag");
        fejlec.add("FixIP");

        ASzerzodes szerzz = new ASzerzodes();
        Vector szolgCsom = new Vector();
        int f = Integer.parseInt(tfValasztott.getText());
        szolgCsom = szerzz.csomagok(f);
        tableSzerzodes.setModel(new DefaultTableModel(szolgCsom, fejlec));


    }//GEN-LAST:event_btSelectActionPerformed

    private void szolgValasztActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_szolgValasztActionPerformed
        if (szolgList.getSelectedValue().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nem választottál szolgáltatást!");
        } else {
            Vector<String> fejlec = new Vector<>();
            fejlec.add("Azonosító");
            fejlec.add("Csomag neve");
            fejlec.add("Havi díj");

            String valasztott = szolgList.getSelectedValue();

            if (valasztott.equals("TV")) {
                ATv tv = new ATv();
                Vector szolgCsom = new Vector();
                szolgCsom = tv.csomagok();
                csomagok.setModel(new DefaultTableModel(szolgCsom, fejlec));
            } else if (valasztott.equals("Telefon")) {
                ATelefon tv = new ATelefon();
                Vector szolgCsom = new Vector(tv.csomagok());
                csomagok.setModel(new DefaultTableModel(szolgCsom, fejlec));
            } else if (valasztott.equals("Internet")) {
                ANet tv = new ANet();
                Vector szolgCsom = new Vector(tv.csomagok());
                csomagok.setModel(new DefaultTableModel(szolgCsom, fejlec));
            }

        }
    }//GEN-LAST:event_szolgValasztActionPerformed

    private void SzerzSzelektActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SzerzSzelektActionPerformed
        String sz = tfValasztottSzerzodes.getText();
        ASzerzodes szam = new ASzerzodes();
        if (sz.isEmpty()) {
            int szersz = szam.generalSzerSzam();

            tfValasztottSzerzodes.setText(String.valueOf(szersz));
            kiSzerSzam.setText(String.valueOf(szersz));
        } else {
            kiSzerSzam.setText(sz);
        }


    }//GEN-LAST:event_SzerzSzelektActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        if (tfValasztottSzerzodes.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nem választottál csomagot!");
        } else {
            ASzerzodes szerz = new ASzerzodes();
            int szerszam1 = Integer.parseInt(kiSzerSzam.getText());
            int csomag1 = Integer.parseInt(tfvalasztottCsomag.getText());
            int folyo1 = Integer.parseInt(tfValasztott.getText());

            szerz.felveszSzolgaltatas(szerszam1, csomag1, folyo1);
            Kedvezmeny kedv = new Kedvezmeny();
            kedv.kedvezmenyBeallit(szerszam1);
            this.dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (tfValasztottSzerzodes.getText().isEmpty()) {
            JOptionPane.showMessageDialog(rootPane, "Nem választottál csomagot!");
        } else {
            ASzerzodes szerz1 = new ASzerzodes();
            int szerszam1 = Integer.parseInt(kiSzerSzam.getText());
            int csomag1 = Integer.parseInt(tfvalasztottCsomag.getText());
            int folyo1 = Integer.parseInt(tfValasztott.getText());
            Egyenleg egy = new Egyenleg();
            double egyen = egy.egyenleg(szerszam1);
            if (egyen < 0) {
                JOptionPane.showMessageDialog(rootPane, "Tartozásod van ezen a " + kiSzerSzam.getText()
                        + " számú szerződéseden!\n Addig nem mondhatsz le szolgáltatást! FIZESS!!");
            } else {
                szerz1.torolSzolgaltatas(szerszam1, csomag1);
                Kedvezmeny kedv = new Kedvezmeny();
                kedv.kedvezmenyBeallit(szerszam1);
                this.dispose();
            }

        }
    }//GEN-LAST:event_jButton4ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SzolgFelvetel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SzolgFelvetel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SzolgFelvetel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SzolgFelvetel.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SzolgFelvetel().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton SzerzSzelekt;
    private javax.swing.JButton btSelect;
    private javax.swing.JTable csomagok;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JLabel kiSzerSzam;
    private javax.swing.JList<String> szolgList;
    private javax.swing.JButton szolgValaszt;
    private javax.swing.JTable table;
    private javax.swing.JTable tableSzerzodes;
    private javax.swing.JTextField tfFolyo;
    private javax.swing.JTextField tfNev;
    private javax.swing.JTextField tfValasztott;
    private javax.swing.JTextField tfValasztottSzerzodes;
    private javax.swing.JTextField tfuzi;
    private javax.swing.JTextField tfvalasztottCsomag;
    // End of variables declaration//GEN-END:variables

    private void executeHQLQuery(String hql) {

        Session session = NewHibernateUtil.getSessionFactory().openSession();
        try {

            session.beginTransaction();
            Query q = session.createQuery(hql);
            List list = q.list();
            displayResult(list);
            session.getTransaction().commit();
            System.out.println(list.size());

        } catch (HibernateException he) {
            he.printStackTrace();
        } finally {
            session.close();
        }
    }

    private void displayResult(List list) {
        Vector<String> fejlec = new Vector<>();
        Vector<Object> adatok = new Vector<>();
        fejlec.add("Folyószámla");
        fejlec.add("Név");
        fejlec.add("Cím");

        for (Object object : list) {
            Ugyfel u = (Ugyfel) object;
            Vector<Object> egySor = new Vector<>();
            egySor.add(u.getFolyosz());
            egySor.add(u.getNev());
            egySor.add(u.getCim());

            adatok.add(egySor);
            if (list.size() == 1) {
                tfValasztott.setText((Integer.toString(u.getFolyosz())));

            } else {
                tfuzi.setText("Kérem válassza ki a folyószámlát és írja be az alábbi mezőbe");
            }

        }

        table.setModel(new DefaultTableModel(adatok, fejlec));

    }
}
