package Data;
// Generated Aug 2, 2016 9:44:35 PM by Hibernate Tools 4.3.1



/**
 * Net generated by hbm2java
 */
public class Net  implements java.io.Serializable {


     private int netid;
     private String netcsnev;
     private int nethdij;
     

    public Net() {
    }

	
    public Net(int netid, String netcsnev, int nethdij) {
        this.netid = netid;
        this.netcsnev = netcsnev;
        this.nethdij = nethdij;
    }
    public Net(int netid, String netcsnev, int nethdij, String ipcim) {
       this.netid = netid;
       this.netcsnev = netcsnev;
       this.nethdij = nethdij;
       
    }
   
    public int getNetid() {
        return this.netid;
    }
    
    public void setNetid(int netid) {
        this.netid = netid;
    }
    public String getNetcsnev() {
        return this.netcsnev;
    }
    
    public void setNetcsnev(String netcsnev) {
        this.netcsnev = netcsnev;
    }
    public int getNethdij() {
        return this.nethdij;
    }
    
    public void setNethdij(int nethdij) {
        this.nethdij = nethdij;
    }
    




}


