package Data;
// Generated Aug 2, 2016 9:44:35 PM by Hibernate Tools 4.3.1



/**
 * Szerzodes generated by hbm2java
 */
public class Szerzodes  implements java.io.Serializable {


     private int szerszam;
     private int folyosz;
     private double egyenleg;
     private double kedvezmeny;
     private int tv;
     private int telefon;
     private int internet;
     private int fixip;
     private double havidij;

    public double getHavidij() {
        return havidij;
    }

    public void setHavidij(double havidij) {
        this.havidij = havidij;
    }
     

    public Szerzodes() {
    }

	
    public Szerzodes(int szerszam, int folyosz, double egyenleg) {
        this.szerszam = szerszam;
        this.folyosz = folyosz;
        this.egyenleg = egyenleg;
    }
    public Szerzodes(int szerszam, int folyosz, double egyenleg, int kedvezmeny, int tv, int telefon, int internet, int fixip, double havidij) {
       this.szerszam = szerszam;
       this.folyosz = folyosz;
       this.egyenleg = egyenleg;
       this.kedvezmeny = kedvezmeny;
       this.tv = tv;
       this.telefon = telefon;
       this.internet = internet;
       this.fixip = fixip;
       this.havidij = havidij;
    }

    public int getSzerszam() {
        return szerszam;
    }

    public void setSzerszam(int szerszam) {
        this.szerszam = szerszam;
    }

    public int getFolyosz() {
        return folyosz;
    }

    public void setFolyosz(int folyosz) {
        this.folyosz = folyosz;
    }

    public double getEgyenleg() {
        return egyenleg;
    }

    public void setEgyenleg(double egyenleg) {
        this.egyenleg = egyenleg;
    }

    public double getKedvezmeny() {
        return kedvezmeny;
    }

    public void setKedvezmeny(double kedvezmeny) {
        this.kedvezmeny = kedvezmeny;
    }

    public int getTv() {
        return tv;
    }

    public void setTv(int tv) {
        this.tv = tv;
    }

    public int getTelefon() {
        return telefon;
    }

    public void setTelefon(int telefon) {
        this.telefon = telefon;
    }

    public int getInternet() {
        return internet;
    }

    public void setInternet(int internet) {
        this.internet = internet;
    }

    public int getFixip() {
        return fixip;
    }

    public void setFixip(int fixip) {
        this.fixip = fixip;
    }
   
   


}


