package Data;
// Generated Aug 2, 2016 9:44:35 PM by Hibernate Tools 4.3.1



/**
 * Telefon generated by hbm2java
 */
public class Telefon  implements java.io.Serializable {


     private int tid;
     private String csnev;
     private int thdij;

    public Telefon() {
    }

    public Telefon(int tid, String csnev, int thdij) {
       this.tid = tid;
       this.csnev = csnev;
       this.thdij = thdij;
    }
   
    public int getTid() {
        return this.tid;
    }
    
    public void setTid(int tid) {
        this.tid = tid;
    }
    public String getCsnev() {
        return this.csnev;
    }
    
    public void setCsnev(String csnev) {
        this.csnev = csnev;
    }
    public int getThdij() {
        return this.thdij;
    }
    
    public void setThdij(int thdij) {
        this.thdij = thdij;
    }




}


