package Data;
// Generated Aug 2, 2016 9:44:35 PM by Hibernate Tools 4.3.1

import Hibernate.NewHibernateUtil;
import Logic.AUgyfel;
import java.util.List;
import org.hibernate.Query;
import org.hibernate.Session;




/**
 * ugyfel generated by hbm2java
 */
public class Ugyfel  implements java.io.Serializable {


     private int folyosz;
     private String nev;
     private String cim;
     private int statusz ;

    public Ugyfel() {  
      
      
    }

    public Ugyfel(int folyosz, String nev, String cim, int statusz) {
       this.folyosz = folyosz;
       this.nev = nev;
       this.cim = cim;
       this.statusz = statusz;
    }
   
    public int getFolyosz() {
        return this.folyosz;
    }
    
    public void setFolyosz(int folyosz) {
        this.folyosz = folyosz;
    }
    public String getNev() {
        return this.nev;
    }
    
    public void setNev(String nev) {
        this.nev = nev;
    }
    public String getCim() {
        return this.cim;
    }
    
    public void setCim(String cim) {
        this.cim = cim;
    }
    public int getStatusz() {
        return this.statusz;
    }
    
    public void setStatusz(int statusz) {
        this.statusz = statusz;
    }




}


